### ISSUE TITLE
Problem in library libswiftQuartzCore

### ISSUE THREAD

**Issue by homerokzam** [Flash3001/Xamarin.Swift#1]
I'm trying to use a library that needs the libswiftQuartzCore library. Is there any support forecast for this library?

Thanks,
Homero.

**Comment by Flash3001** [comment]
Hey @homerokzam 

Just updated all packages to support Xcode 8.1
QuartzCore was introduced in it. 

You can find the package in https://www.nuget.org/packages/Xamarin.Swift3.QuartzCore/

**Comment by homerokzam** [comment]
Thank you Lucas.
