### ISSUE TITLE
Metal package missed reference to OS package

### ISSUE THREAD

**Issue by tuyen-vuduc** [Flash3001/Xamarin.Swift#10]
Plz add package dependency:
- target: Xamarin.Swift4.Metal
- depedency: Xamarin.Swift4.OS

**Comment by Flash3001** [comment]
@tuyen-vuduc you need to add that dependency directly to the final App. There are no dependencies added between the packages in NuGet. I thought in doing it, but it would make it more complicated for me when pushing a new release (its 40 packages).

**Comment by tuyen-vuduc** [comment]
I know, but it's much better for folks when using your package. Folks don't know packages missing until building error. It's hard for beginner absolutely.
