### ISSUE TITLE
The document is closed

### ISSUE THREAD

**Issue by crazydragon91** [Flash3001/Xamarin.Swift#11]
Hi,

Stackoverflow now closed http://stackoverflow.com/documentation/xamarin.ios/6091/binding-swift-libraries. Can you rewrite this?

Thanks,

**Comment by Flash3001** [comment]
Hi @crazydragon91 

You can read it in here https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76
