### ISSUE TITLE
Binding Xamarin.Swift4

### ISSUE THREAD

**Issue by bulubuloa** [Flash3001/Xamarin.Swift#13]
Can you binding a new update for Xamarin.Swift4, i have XCode 9.3.2 and Swift 4.0.3, everything work fine but i can extract and copy lib to upload app to appstore

`Invalid Swift Support - The files libswiftos.dylib, libswiftCoreGraphics.dylib, libswiftQuartzCore.dylib, libswiftCoreFoundation.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftCoreImage.dylib, libswiftCoreMedia.dylib, libswiftCoreData.dylib, libswiftMetal.dylib, libswiftDarwin.dylib, libswiftCoreAudio.dylib, libswiftUIKit.dylib, libswiftDispatch.dylib, libswiftObjectiveC.dylib don’t match /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftos.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftQuartzCore.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCore.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftFoundation.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreImage.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreMedia.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreData.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftMetal.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftDarwin.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreAudio.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftUIKit.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftDispatch.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftObjectiveC.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftos.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftQuartzCore.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCore.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftFoundation.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreImage.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreMedia.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreData.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftMetal.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftDarwin.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftCoreAudio.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftUIKit.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftDispatch.dylib, /Payload/bxoiCrypto.iOS.app/Frameworks/libswiftObjectiveC.dylib.
`

**Comment by Flash3001** [comment]
@bulubuloa Version 9.3 is still in beta, latest public version is 9.2. Are you using the beta version?

**Comment by bulubuloa** [comment]
sorry for late feedback, i fixed my problems, just update ioschart for compatible with swift library :)
