### ISSUE TITLE
Problems on publishing app using Xamarin.Swift3 support from Apple (CI/CD pipeline)

### ISSUE THREAD

**Issue by stvansolano** [Flash3001/Xamarin.Swift#16]
Hello @Flash3001 have you guys tried publishing apps with Xamarin.Swift3 packages? I tried recently with a binding library that depends on [Xamarin.Swift3.Support](https://github.com/Flash3001/Xamarin.Swift3.Support) but unfortunately it doesn't get processed by Apple correctly.

Is there a workaround that you guys would recommend for making `ipa-packager` process for CI/CD pipelines? Here is the text I get from Apple team in case anyone takes the same.

> Dear Developer,
>
>We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.
>
>Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
>
>Best regards,
>
>The App Store Team

After removing the binding and the Xamarin.Swift3 references it gets processed. I saw some workarounds on copying the missing folders but didn't like doing that or block CI/CD scenarios

**Comment by stvansolano** [comment]
Moving to use IPA packager for solving that.

https://github.com/Flash3001/ipa-packager

A way to have that as CI/CD for IPAs would be helpful :)

**Comment by Flash3001** [comment]
Hey @stvansolano 

I'm not sure I understood the issue. 

We make it work in our CI by adding a call to the *ipa-packager* script as a new step right after the compilation process. So as soon as we get the IPA we run the script and get a new one.
