### ISSUE TITLE
Using with Xamarin.Forms

### ISSUE THREAD

**Issue by Niach** [Flash3001/Xamarin.Swift#17]
Hey! I made a Binding of TrustSDK (Nuget: TrustSDK.Xamarin.iOS) using your guide, and it all works well when using it in an Xamarin.iOS project. But when i do the same on the iOS sub-project of an Xamarin.Forms app the app does not start and gives the following output:
`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/XXX/Library/Developer/CoreSimulator/Devices/AE976B11-BA9B-4A9A-BCD8-BD25CEB4FB9E/data/Containers/Bundle/Application/E9DCCADA-C7E6-40D3-86E1-61C2B6F6FB04/testtesttest.iOS.app/Frameworks/BigInt.framework/BigInt
  Reason: no suitable image found.  Did find:
	/Users/XXX/Library/Developer/CoreSimulator/Devices/AE976B11-BA9B-4A9A-BCD8-BD25CEB4FB9E/data/Containers/Bundle/Application/E9DCCADA-C7E6-40D3-86E1-61C2B6F6FB04/testtesttest.iOS.app/Frameworks/libswiftCore.dylib: no matching architecture in universal wrapper
	/Users/XXX/Library/Developer/CoreSimulator/Devices/AE976B11-BA9B-4A9A-BCD8-BD25CEB4FB9E/data/Containers/Bundle/Application/E9DCCADA-C7E6-40D3-86E1-61C2B6F6FB04/testtesttest.iOS.app/Frameworks/libswiftCore.dylib: stat() failed with errno=45
	/Users/XXX/Library/Developer/CoreSimulator/Devices/AE976B11-BA9B-4A9A-BCD8-BD25CEB4FB9E/data/Containers/Bundle/Application/E9DCCADA-C7E6-40D3-86E1-61C2B6F6FB04/testtesttest.iOS.app/Frameworks/libswiftCore.dylib: no matching architecture in universal wrapper`
The lib is written in Swift 4.1 and I'm using your newest Swift4 packages.

**Comment by Flash3001** [comment]
Hey @Niach, I never worked with Xamarin.Forms before, but based on the message it seems the code for MSBuild responsible for copying the Simulator frameworks from the SimulatorFrameworks folder to the  Frameworks folder is not running. 

If you deploy to a device it works? If I'm correct it should as this project puts the Device files in the Frameworks folder by default. 

When you add the Xamarin.Swift4 base package it changes you .csproj to run this file manipulation code. 

You can find a line like this one in your .csproj 
```<Import Project="..\packages\Xamarin.Swift4.4.0.0.0\build\Xamarin.Swift4.targets" Condition="Exists('..\packages\Xamarin.Swift4.4.0.0.0\build\Xamarin.Swift4.targets')" />```

Please check the Xamarin.Forms project to see if it includes this line and if it runs on the Device.

**Comment by gmoney494** [comment]
I also have a similar issue with the same crash report on my custom binding for a library partially written in swift. My .csproject did not have the line you mentioned @Flash3001. I added it and i still get the same error (I did have to change the file location to the global nuget packages folder since i dont have a local project one). Not sure what else i can do to get past this. 

PS. Ive added the necessary swift libraries using the otool to figure out the depedencies. Also using swift 4 packages. This is also a xamarin forms app. Without the libswiftcore , i get the library missing error, with them, now it says wrong architecture. this is for running on the simulator, the framework contains the x86_64 simulator architecture.

**Comment by Flash3001** [comment]
Hey @gmoney494. 

The crash is complain the Swift libraries contains the wrong architecture or your binding library itself?  

What happens if you try to run on a real device?

**Comment by valentingrigorean** [comment]
Hey editing csproj and adding `<Import Project="..\packages\Xamarin.Swift4.4.0.0.0\build\Xamarin.Swift4.targets" Condition="Exists('..\packages\Xamarin.Swift4.4.0.0.0\build\Xamarin.Swift4.targets')" />` did fix my problem. Be careful with the path to packages to be correct.

Thanks @Flash3001
