### ISSUE TITLE
Leveraging this for macOS targets?

### ISSUE THREAD

**Issue by someone29926** [Flash3001/Xamarin.Swift#2]
I'm curious if you know whether this work could be used directly (or adapted somehow) for macOS target applications? I am getting a lot of the same errors as would be expected when trying to use a Swift3 based framework for a macOS target and it seems like the basic concept to getting bindings, etc. to work would be the same. Or am I maybe underestimating some additional challenges there?

**Comment by Flash3001** [comment]
@someone29926 This is veeeeeeery delayed reply, but I am currently working on a version that should give support for macOS when targetting a version lower than 10.14.4. It should be out soon.

**Comment by Flash3001** [comment]
Experimental support have was added to https://www.nuget.org/packages/Xamarin.Swift/
