### ISSUE TITLE
Invalid Swift support

### ISSUE THREAD

**Issue by fettergabor** [Flash3001/Xamarin.Swift#20]
We have a Xamarin iOS app using a swift iOS framework through a binding library.
Submissions to AppStore were successful before (..until Swift 4.2)
But we get the following error email after submission to AppStore, since Swift 4.2.1 (and corresponding Nugets) were published:

Invalid Swift Support - The files libswiftCoreGraphics.dylib, .. don’t match ... 

Comments:
- We are using the latest toolchain (VS for Mac 7.6.11, Xamarin.iOS 12.1.0.15 , XCode 10.1)
- We updated Xamarin.Swift4.* Nugets to 4.2.1 in our app
- The dylib versions are the same in both the /Frameworks and the SwiftSupport/ folders (i.e. 4.2.1) in the IPA
- We are using the suggested scripts to include SwiftSupport libraries

Note, the submission flow worked fine with 4.2.

Please, kindly help, thanks!!

**Comment by Flash3001** [comment]
Hey @fettergabor can you share the entire AppStore message? Can you tell if that is for all the dylibs or just a subset of the ones you use?  Also, what is the Xcode version, is it 10B61?

**Comment by fettergabor** [comment]
Thank you for the help! 
xCode version is 10B61. AppStore complains for all swift dylibs used in the project.
Here is the complete email:

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Olympus Mobility". Please correct the following issues, then upload again.

Invalid Swift Support - The files libswiftCoreGraphics.dylib, libswiftDarwin.dylib, libswiftos.dylib, libswiftQuartzCore.dylib, libswiftContacts.dylib, libswiftFoundation.dylib, libswiftMetal.dylib, libswiftCoreFoundation.dylib, libswiftCoreImage.dylib, libswiftObjectiveC.dylib, libswiftUIKit.dylib, libswiftDispatch.dylib, libswiftCore.dylib don’t match /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftDarwin.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftos.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftQuartzCore.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftContacts.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftFoundation.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftMetal.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCoreImage.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftObjectiveC.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftUIKit.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftDispatch.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCore.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftDarwin.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftos.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftQuartzCore.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftContacts.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftFoundation.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftMetal.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCoreImage.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftObjectiveC.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftUIKit.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftDispatch.dylib, /Payload/OlympusMobilityTouch.app/Frameworks/libswiftCore.dylib.

Best regards,

The App Store Team

**Comment by Flash3001** [comment]
@fettergabor I was having the same issue. On Xcode 10.1 the arm64e architecture was included in the Swift dylibs. For previous releases only copying the .dylibs from the Xcode folder and publishing the packages would do the trick, but this time it didn't work. I created a sample project on Xcode and created the IPA to check what Xcode was doing and it was stripping the arm64e architecture from the dylibs on the Frameworks folder. Then I did the same for the SwiftSupport packages and it worked - armv7 armv7s arm64 are still available as before.

I don't know why Apple is not accepting the dylibs with arm64e included on the Frameworks folder. The ones on SwiftSupport folder outside the .app (created by the script) still need to contain it though. App Store message is not clear.

The new packages are uploaded to Nuget. Please let me know if it fixes the problem for you.

**Comment by fettergabor** [comment]
I could upload the app to AppStore successfully using the updated NuGets (v4.2.1.1).
Many thanks for your help! :-)
