### ISSUE TITLE
with Xamarin.Swift version 4.0.0.2 I'm no more able to install the app on device 

### ISSUE THREAD

**Issue by nobreak** [Flash3001/Xamarin.Swift#25]
with Xamarin.Swift version 4.0.0.2 I'm no more able to install the app on a device. I get the error 

"ApplicationVerificationFailed: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.23HY8f/extracted..... : 0xe8008015 (A valid provisioning profile for this executable was not found.)
error MT1006: Could not install the application ...... on the device 'iPhone XS 01': AMDeviceSecureInstallApplicationBundle returned: 0xe8008015." 

in the Deploying to Device log.

I could fix it when I downgrade back to 4.0.0.1.

It only happens in release mode with real devices.

**Comment by Flash3001** [comment]
Thanks for the report @nobreak. Are you using VS for Windows or Mac?

**Comment by nobreak** [comment]
I’m using VS on Mac

**Comment by Flash3001** [comment]
@nobreak were you able to verify if you invalid signature problem was indeed caused by this version 4.0.0.2? I didn't see any other report of invalid signatures due to that. I was expecting it to gather more information about the issue.

**Comment by Jakar510** [comment]
I've getting this issue with Visual Studio 2019 (16.3.6) on bebug over wifi.

"Launch failed. The app 'appName.iOS' could not be launched on 'iPhone'. Error: error MT1006: Could not install the application '/Users/user/Library/Caches/Xamarin/mtbs/builds/appName.iOS/8eebc767bbc13df57b4dea7646809dd2/bin/iPhone/Debug/appName.iOS.app' on the device 'iPhone': AMDeviceSecureInstallApplicationBundle returned: 0xe8008015.. Please check the logs for more details."

**Comment by sourav-prescriber-360** [comment]
I was facing the same issue.

> Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.7tSF0m/extracted/Payload/DCR_Sales.iOS.app : 0xe8008017 (A signed resource has been added, modified, or deleted.), LegacyErrorString=ApplicationVerificationFailed, FunctionName=+[MICodeSigningVerifier

The app was working fine on the simulator but when release build was created and installed on the device. It throws error Unable to install. Please try again later. I have also downgraded the build as suggested above and it's running fine now.
