### ISSUE TITLE
swift 5

### ISSUE THREAD

**Issue by wuhuangjia** [Flash3001/Xamarin.Swift#27]
Hello @Flash3001 , first, thank you for your great work, let us have great toolkit can finish our job, and do you have any plan about swift 5?

**Comment by Flash3001** [comment]
Hey @wuhuangjia. I do, please read this comment: https://github.com/Flash3001/Xamarin.SwiftSupport/issues/21#issuecomment-477792723

I will try to publish it this week.

**Comment by wuhuangjia** [comment]
hello~ thanks a lot, sorry I just find you already create swift5 folder, thanks again~~

**Comment by Flash3001** [comment]
Hey @wuhuangjia the project has been published to Nuget as Xamarin.Swift http://nuget.org/packages/Xamarin.Swift/

I still need to provide some documentation on it.
