### ISSUE TITLE
CoreAnimation framework missing

### ISSUE THREAD

**Issue by Tylerian** [Flash3001/Xamarin.Swift#3]
CoreAnimation's swift framework is missing. Any plans on adding it?

**Comment by Flash3001** [comment]
@Tylerian it's included in QuartzCore

http://stackoverflow.com/questions/729094/how-can-i-add-core-animation-framework-to-my-xcode-project

https://developer.apple.com/reference/quartzcore

If you go to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/QuartzCore.framework/Headers you will see they are related to CoreAnimation
