### ISSUE TITLE
ITMS-90428: Invalid Swift Support - The files.... dont match

### ISSUE THREAD

**Issue by fettergabor** [Flash3001/Xamarin.Swift#34]
I get the above error when I try to submit my app to the Store.
I use the latest VS (8.1.1), latest xCode (10.2.1) and the latest Xamarin.Swift.
I also used the auto_package_ipa script too, since the "SwiftSupport" folder was not there after the build.

I checked the dylibs:

- The dylib file versions match (v5.0.1) both in "SwiftSupport" and "Frameworks" folders
- The dlybs in "SwiftSupport" folder contain 4 architectures: armv7, armv7s, arm64, arm64e
- The dlybs in "Framework" folder contain 1 architecture: arm64

The README.md here says, that the included architectures should match. How to achieve this?

**Comment by fettergabor** [comment]
More observations:
- If I use a Swift 5 based 3rd party library in the project and don't use Xamarin.swift Nuget and don't repack the IPA with SwiftSupport folder, then the app works on iOS 12.2 and later, but crashes on earlier iOS versions
- If I use Swift 4.2.1 based version of the same library,  and use Xamarin.Swift4.* Nuget, and repack the IPA with SwiftSupport folder, it crashes on iOS 12.2 and later, but works on earlier iOS versions!

**Comment by Kingamattack** [comment]
Hi, did you manage to fix that issue? 

I have the same thing when I try to submit a Xamarin.iOS app using a Binding swift library. 
I used several workarounds
https://stackoverflow.com/questions/53214530/invalid-swift-support-files-dont-match-xcode-10-1
https://stackoverflow.com/questions/37820300/invalid-swift-support-using-native-swift-library-in-xamarin-ios/47948277#47948277 but none of them was efficient for me...

**Comment by Flash3001** [comment]
@fettergabor @Kingamattack I am really sorry for the long delay to reply - lots going on in here - there is an updated version of the *auto_package_ipa* script you can use to remove the extra archs.

https://github.com/Flash3001/ipa-packager/blob/master/package_ipa_default.sh

**Comment by huszarg** [comment]
@Flash3001 When I created an app package with the latest version of the Xamarin.Swift the app only work on 12.2 or later and crashes on earlier version iOS versions. In this case the app package is not included the "SwiftSupport" folder. How to repack the app package to work on all iOS versions?

**Comment by fettergabor** [comment]
@Flash3001 Thank you! The script worked. (To be exact, we copied the relevant part into our script, that removes the unnecessary architectures from the dlybs.) This way the app works fine with any iOS version.
