### ISSUE TITLE
Incompatible with project.json

### ISSUE THREAD

**Issue by stopiccot** [Flash3001/Xamarin.Swift#4]
Dunno if it's a package problem or a xamarin one but when using your packages in a project.json project Xamarin.Swift3.targets seems to be ignored and in a simulator build arm frameworks are not overwritten with x86 ones.

**Comment by Flash3001** [comment]
Are you including the library as a Package Reference in a new library? I suppose so based on the use of project.json. The ideal is to include it as Dependency in your NuGet package so it is added directly to the final Xamarin.iOS project. If you aren't creating a NuGet package, reference it in the iOS project.

**Comment by mrbiggred** [comment]
I was able to duplicate @stopiccot problem.  I created a Xamarin Forms project and converted the iOS and portable project json.  When I run the application in debug on the simulator I got the following error:

    Library not loaded: <My library>
    Reason: no suitable image found.  Did find:
      /.../libswiftCore.dylib: no matching architecture in universal wrapper.

When I inspected libswiftCore.dylib the file in the folder:

    /Users/<user>/Library/Developer/CoreSimulator/Devices/<GUID>/Containers/Bundle/
    Application/<GUID>/<App` Name>/Frameworks

I found it was arm and not x86/x64:

    file libswiftCore.dylib

I then created another iOS project and left it as standard NuGet.  I then added a reference to the same binding library.  When I run this project it works as expected and the correct dylib files are copied over.  

Thank you for creating these Swift bindings.  Let me know if you need any other information.

**Comment by ghost** [comment]
@mrbiggred do you have an example of what your work around/solution like? i'm getting the simulator deployment issues in my solution as well. And i don't quite understand what you were explaining above.

**Comment by ghost** [comment]
Oh, wait. Rereading everything it sounds like we need to use packages.config instead of project.json for nuget references. 

Can someone confirm that to be the case?

**Comment by mrbiggred** [comment]
@keannan5390 you are correct that you need to use packages.config instead of project.json.  At least that was the fix that worked for me.  

Sorry I don't have an example.  Originally I was going to use a iOS checkbox written in Swift but switched to one written in objective-c so I no longer need to import the Swift Support packages.

**Comment by ghost** [comment]
thanks @mrbiggred. I got it working, with packages.config.

**Comment by ghost** [comment]
has there been any updates on this? i'd really like to move off packages.config if at all possible.

do we still need packages.config?

**Comment by Flash3001** [comment]
@ghost project.json was replaced by PackageReferece on the .csproj  . Is that working for you?

**Comment by thefex** [comment]
@Flash3001 this does not work for me as well (simulator crashes), I use PackageReference

I guess .TARGETS does not work the same with .NetStandard?

**Comment by Flash3001** [comment]
This issue is a bit old and other with the same root cause were created. 

I added a comment on https://github.com/Flash3001/iOSCharts.Xamarin/issues/47#issuecomment-452548254 with a workaround for it.

I believe to have found the real solution, it is already pushed to the repo, but I want to do more testing before pushing to NuGet.
