### ISSUE TITLE
Paths to swift dylibs are different in XCode 11

### ISSUE THREAD

**Issue by jahmai-ca** [Flash3001/Xamarin.Swift#42]
Old paths were:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos

New paths are:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos

**Comment by jahmai** [comment]
No I'm wrong, XCode 11 is just missing swift 3/4 libs.

**Comment by jahmai** [comment]
For swift 5 though they are in this folder:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos

**Comment by jahmai-ca** [comment]
NOTE: I ended up copying the iphoneos folder from XCode 10 across to XCode 11 in the same location to get our builds working, because I wasn't confident using the Swift 5 ones was the right thing to do.

**Comment by Flash3001** [comment]
Thanks for notifying about it @jahmai. I am changing the script to take it into consideration when using Xcode 11 and will be pushing an update.

**Comment by Flash3001** [comment]
Published it as version 1.0.4. Please let me know if it fixes the issue for you.

**Comment by Kingamattack** [comment]
> Published it as version 1.0.4. Please let me know if it fixes the issue for you.

Hi @Flash3001, does it means that we can update VS4Mac and Xcode to the latest versions and compile using Swift 5.1? Or we still have to use Swift 5?

I remember that some of us had troubles when they try to use Swift 5.0.1 instead of 5

**Comment by jahmai-ca** [comment]
I can confirm that the new package works with XCode 11! Closing issue :)
