### ISSUE TITLE
MSB4044: The "CheckSwiftVersionsTask" task was not given a value for the required parameter "SdkVersion"

### ISSUE THREAD

**Issue by SangI762** [Flash3001/Xamarin.Swift#49]
I just updated VS Mac, Xamarin.iOS and getting this error when compile.

`/.nuget/packages/xamarin.swift/1.0.5/build/xamarinios/Xamarin.Swift.targets(9,9): Error MSB4044: The "CheckSwiftVersionsTask" task was not given a value for the required parameter "SdkVersion". (MSB4044) `

**Versions info:**
=== Visual Studio Community 2019 for Mac ===

Version 8.8 (build 2913)
Installation UUID: cb7b1221-47b9-4215-9549-e24397200261
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.2.104
	2.1.809
	2.1.505
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.2.2
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.9
	2.1.2
	2.1.1
	2.0.5

=== .NET Core 3.1 SDK ===

SDK: 3.1.403

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.1 (17222)
Build 12A7403

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.4.1.3 (Visual Studio Community)
Hash: e30c41de3
Branch: d16-8
Build date: 2020-10-20 22:18:50-0400

=== Xamarin Designer ===

Version: 16.8.0.495
Hash: 1a7425b8f
Branch: remotes/origin/d16-8
Build date: 2020-10-20 10:51:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/ignasbagdonas/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ignasbagdonas/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808002913
Git revision: c6189b3851aed1e1aadbef5807d54bd5bb505e5e
Build date: 2020-11-05 07:07:20-05
Build branch: release-8.8
Xamarin extensions: c6189b3851aed1e1aadbef5807d54bd5bb505e5e

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Mutatio 1.0.3
StyleCop Support 1.1.0.4

**Comment by gmoney494** [comment]
I just got to this exact same issue, not too many threads/posts anywhere about this one issue. Same VS set up as well.

**Comment by SangI762** [comment]
As workaround I downgraded Xamarin.iOS to version: 14.2.0.12 and it works again.

**Comment by gmoney494** [comment]
@ignasbagdonas do you have the link to download it?

**Comment by gmoney494** [comment]
@ignasbagdonas i managed to get it working by adding this in the ios .csproj file `<MtouchSdkVersion>14.1</MtouchSdkVersion>`. I did it by not using the Default option under iOS Options (project options) -> iOS Build -> SDK Version: (not Default).

**Comment by Dona278** [comment]
Same issue...
And (for now) solved with @gmoney494 workaround!

**Comment by SangI762** [comment]
Yes. @gmoney494 workaround worked for me as well.

**Comment by SangI762** [comment]
As we have setting through IDE and it fix error I should close issue.

**Comment by gmoney494** [comment]
@ignasbagdonas i would leave it open as this shouldn't be happening, the `Default` setting should work as expected. This still seems like a bug to me.

**Comment by Flash3001** [comment]
Xamarin unified the **MacOSXSdkVersion** and **MtouchSdkVersion** names into **_SdkVersion**

I just pushed version 1.0.6 to NuGet with the fix. 

Please let me know if it worked for you =)

**Comment by gmoney494** [comment]
@Flash3001 ok that seems to be working for me now, ill keep testing. Thanks

**Comment by SangI762** [comment]
@Flash3001 Will it work with older Xamarin.iOS ?

Asking this because in our local machines is latest version, but on CI still 13.7

Update:
`/Users/admin/.nuget/packages/xamarin.swift/1.0.6/build/xamarinios/Xamarin.Swift.targets(34,9): error MSB4044: The "CheckSwiftVersionsTask" task was not given a value for the required parameter "SdkVersion". [/Users/admin/.jenkins/workspace/CityBeeAppTests/CityBee.iOS/CityBee.iOS.csproj]`

As I said, it doesn't work with XCode 11.7 and Xamarin.iOS 13.20.2.2
Could you support both?

**Comment by gmoney494** [comment]
> @Flash3001 Will it work with older Xamarin.iOS ?
> 
> Asking this because in our local machines is latest version, but on CI still 13.7
> 
> Update:
> `/Users/admin/.nuget/packages/xamarin.swift/1.0.6/build/xamarinios/Xamarin.Swift.targets(34,9): error MSB4044: The "CheckSwiftVersionsTask" task was not given a value for the required parameter "SdkVersion". [/Users/admin/.jenkins/workspace/CityBeeAppTests/CityBee.iOS/CityBee.iOS.csproj]`
> 
> As I said, it doesn't work with XCode 11.7 and Xamarin.iOS 13.20.2.2
> Could you support both?

Im having a similar issue. It works locally without my workaround noted above using the updated Xamarin.Swift nuget package (version 1.0.6), using Xamarin.iOS version 14.4.1.3 locally. On App Center however only Xamarin.iOS 14.0 is available. Have not tried my workaround as im avoiding having to hardcode it, update it and then eventually remove it. Not the most efficient solution long term.

**Comment by Flash3001** [comment]
I added a fallback for older versions of Xamarin.iOS that will set _SdkVersion to MtouchSdkVersion value in case it is null.

The updated version is 1.0.7.

Please let me know if it works.

We were having the same issue in our App Center builds. It is working now.

**Comment by gmoney494** [comment]
> I added a fallback for older versions of Xamarin.iOS that will set _SdkVersion to MtouchSdkVersion value in case it is null.
> 
> The updated version is 1.0.7.
> 
> Please let me know if it works.
> 
> We were having the same issue in our App Center builds. It is working now.

@Flash3001 Xamarin.Swift 1.0.7 worked on getting my App Center builds to work. Xamarin.iOS 14.0 and Xcode version 12.1.1. Will continue testing the produced builds for any potential bugs/crashes.

**Comment by umitnuri** [comment]
I was having the same issue. I upgraded to 1.0.7 to fix it. This is now working fine with Azure DevOps. :)

**Comment by SangI762** [comment]
It works for me too. Thanks.
