### ISSUE TITLE
Attempting to JIT compile method ... while running in aot-mode only

### ISSUE THREAD

**Issue by skela** [Flash3001/Xamarin.Swift#5]
I've basically tried to copy the steps you've made in your stackoverflow help post, and look at your sample project. Almost there I reckon, but come across one minor speedbump I think. Did you ever see or come across a similar runtime error ?

	System.ExecutionEngineException: Attempting to JIT compile method 'SwiftUI.TestModel:.ctor ()' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

**Comment by skela** [comment]
Its worth mentioning that the issue is only when building for devices. Seems to work fine for the Simulator.

**Comment by skela** [comment]
Same issue happens in your sample solution here: https://github.com/Flash3001/Xamarin.BindingSwiftLibrarySample

**Comment by Flash3001** [comment]
I was able to reproduce it in here using Debug configuration and 
Mono 5.0.1.1 (2017-02/5077205) (64-bit)
Xamarin.iOS Version: 10.10.0.36

The issue happens to you under a similar setup? I'll see if I can downgrade my Xamarin.iOS to check when/what happened.

**Comment by skela** [comment]
Yup:
Mono 5.0.1.1 (2017-02/5077205) (64-bit)
Xamarin.iOS Version: 10.10.0.36 (Visual Studio Community)

**Comment by Flash3001** [comment]
@skela This issue isn't strictly related to Swift bindings. I tried to reproduce it using the minimal for a Xamarin.iOS binding and it still happens when building for Debug + Device under the same versions.

I filled a bug in Xamarin's Bugzilla and you can check the issue in there https://bugzilla.xamarin.com/show_bug.cgi?id=56962

The way I found to circumvent it at the moment is by subclassing any class you want to use (no need to use the subclass, just to force a Ahead of Time compilation) or run under Release.

**Comment by skela** [comment]
Ok cool, wasn't sure if it was a binding issue or a Xamarin issue. I've raised issues with Xamarin before and its taken them years to fix, but hopefully they are a bit faster now hehe.

Just about the workaround, are you saying that you add a dummy class in c# that inherits from the classes u want to use in Swift? And even if yer not using it, that works because yer forcing Visual studio to compile it all ahead of time, thus avoiding the JIT exception ?

**Comment by Flash3001** [comment]
As far as I could verify, Yes!

But you only need it when running in debug on device.

**Comment by skela** [comment]
Excellent, thx.

I'll close this, as its not related to the binding itself. :)

Thx again for yer help.
