### ISSUE TITLE
Missing libswift_Concurrency.dylib with XCode 15.1

### ISSUE THREAD

**Issue by ssauxescoubet** [Flash3001/Xamarin.Swift#58]
Hello,

We have another problem with XCode 15.1 and Visual Studio 17.6.7.417 
We have library that depends of `libswift_Concurrency.dylib` which is in `swift-5.5` folder
 `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/`. 

But currently, Xamarin.Swift find swift dependencies in `swift-5.0`. With this missing dependency, our application is crashing at startup on iOS 14.

If I copy the library in `swift-5.0` folder, library is include in ipa Frameworks folder and application no longer crashes.
But it is not a clean solution.

Thanks

**Comment by Flash3001** [comment]
@ssauxescoubet closing this issue as fixed I it while handling #57
