### ISSUE TITLE
Failed to codesign libswiftxyz.dylib

### ISSUE THREAD

**Issue by skela** [Flash3001/Xamarin.Swift#8]
Upgraded to the latest version of Visual Studio / Xamarin today, and after that my app will not build anymore. I'm raising it here as it seems to be specific to the libswift stuff.

As far as I can tell, its failing for all the swift packages apart from the Xamarin.Swift4 one.
 
Here's an excerpt of the errors:

	/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error: Failed to codesign 'bin/iPhoneSimulator/Debug/device-builds/iphone9.1-11.0/App.app/Frameworks/libswiftCore.dylib': bin/iPhoneSimulator/Debug/device-builds/iphone9.1-11.0/App.app/Frameworks/libswiftCore.dylib: replacing existing signature
	bin/iPhoneSimulator/Debug/device-builds/iphone9.1-11.0/App.app/Frameworks/libswiftCore.dylib: unknown error -1=ffffffffffffffff (App)

**Comment by Flash3001** [comment]
@skela Have you tried remove the **bin** and **obj** folders? I also upgraded and it is working for both Simulator and Device.

**Comment by skela** [comment]
@Flash3001 sorry about that. Turns out there is something wrong in either Xcode or Visual Studio for Mac. I keep finding my apple development account missing from the accounts list, and I've obviously not touched it. Happened to my colleagues as well. Anyway, its clearly not a bug with this stuff, so will close the issue.
