### ISSUE TITLE
Invalid Swift Support error Xcode 9.2

### ISSUE THREAD

**Issue by skela** [Flash3001/Xamarin.Swift#9]
Getting Invalid Swift Support again

	Dear developer,

	We have discovered one or more issues with your recent delivery for "App X". To process your delivery, the following issues must be corrected:

	Invalid Swift Support - The files libswiftDarwin.dylib, libswiftCoreFoundation.dylib, libswiftQuartzCore.dylib, libswiftFoundation.dylib, libswiftCoreAudio.dylib, libswiftCoreGraphics.dylib, libswiftMetal.dylib, libswiftCore.dylib, libswiftCoreImage.dylib, libswiftDispatch.dylib, libswiftObjectiveC.dylib, libswiftCoreMedia.dylib, libswiftUIKit.dylib, libswiftos.dylib don?t match /Payload/App.X.app/Frameworks/libswiftDarwin.dylib, /Payload/App.X.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/App.X.app/Frameworks/libswiftQuartzCore.dylib, /Payload/App.X.app/Frameworks/libswiftFoundation.dylib, /Payload/App.X.app/Frameworks/libswiftCoreAudio.dylib, /Payload/App.X.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/App.X.app/Frameworks/libswiftMetal.dylib, /Payload/App.X.app/Frameworks/libswiftCore.dylib, /Payload/App.X.app/Frameworks/libswiftCoreImage.dylib, /Payload/App.X.app/Frameworks/libswiftDispatch.dylib, /Payload/App.X.app/Frameworks/libswiftObjectiveC.dylib, /Payload/App.X.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.X.app/Frameworks/libswiftUIKit.dylib, /Payload/App.X.app/Frameworks/libswiftos.dylib. 

	Make sure the files are correct, rebuild your app, and resubmit it. Don?t apply post-processing to /Payload/App.X.app/Frameworks/libswiftDarwin.dylib, /Payload/App.X.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/App.X.app/Frameworks/libswiftQuartzCore.dylib, /Payload/App.X.app/Frameworks/libswiftFoundation.dylib, /Payload/App.X.app/Frameworks/libswiftCoreAudio.dylib, /Payload/App.X.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/App.X.app/Frameworks/libswiftMetal.dylib, /Payload/App.X.app/Frameworks/libswiftCore.dylib, /Payload/App.X.app/Frameworks/libswiftCoreImage.dylib, /Payload/App.X.app/Frameworks/libswiftDispatch.dylib, /Payload/App.X.app/Frameworks/libswiftObjectiveC.dylib, /Payload/App.X.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.X.app/Frameworks/libswiftUIKit.dylib, /Payload/App.X.app/Frameworks/libswiftos.dylib.

	Once these issues have been corrected, you can then redeliver the corrected binary.

	Regards,

	The App Store team

**Comment by skela** [comment]
Started happening after upgrading to Xcode 9.0.1. Does it mean every time there is an xcode upgrade, we will have the Invalid Swift Support issue crop up again?

**Comment by Flash3001** [comment]
Hey @skela , yes! Every Xcode version comes with a new set of libraries so you need to update the packages if you update your build server.

I usually update it within 1 or 2 days after the release, but this time I missed it, sorry! The new packages are being uploaded right now. I was not able to test it yet (the only way to be sure is submitting the app to App Store) so please let me know if everything goes right.

**Comment by skela** [comment]
Was going to raise an issue, but saw I'd forgotten the issue from a previous update, so I'll just rename this one ;)

**Comment by alexlopespereira** [comment]
Hi,

I have this very same issue. And I did not get from the comments above how to fix it. Does any one knows how to fix it?
